// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9447dsRx4wGNKUPK3eVvIty2KRfSWjG4',
    appId: '1:406163437554:web:49b0e0dfb0b3c9ee3e1d6b',
    messagingSenderId: '406163437554',
    projectId: 'doc-appoint-2783a',
    authDomain: 'doc-appoint-2783a.firebaseapp.com',
    storageBucket: 'doc-appoint-2783a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANAf_9uaA3Ookm9YEFztIz39cXRoKzeDM',
    appId: '1:406163437554:android:11ee29aefd540dc43e1d6b',
    messagingSenderId: '406163437554',
    projectId: 'doc-appoint-2783a',
    storageBucket: 'doc-appoint-2783a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8bx4I9kg77knYrNRYmdHbxLbCKUur7jo',
    appId: '1:406163437554:ios:cb4904eebdbdd7043e1d6b',
    messagingSenderId: '406163437554',
    projectId: 'doc-appoint-2783a',
    storageBucket: 'doc-appoint-2783a.firebasestorage.app',
    iosBundleId: 'com.example.docAppoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8bx4I9kg77knYrNRYmdHbxLbCKUur7jo',
    appId: '1:406163437554:ios:cb4904eebdbdd7043e1d6b',
    messagingSenderId: '406163437554',
    projectId: 'doc-appoint-2783a',
    storageBucket: 'doc-appoint-2783a.firebasestorage.app',
    iosBundleId: 'com.example.docAppoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9447dsRx4wGNKUPK3eVvIty2KRfSWjG4',
    appId: '1:406163437554:web:2f55dc0a1b4dac6f3e1d6b',
    messagingSenderId: '406163437554',
    projectId: 'doc-appoint-2783a',
    authDomain: 'doc-appoint-2783a.firebaseapp.com',
    storageBucket: 'doc-appoint-2783a.firebasestorage.app',
  );
}
